/* $Header$ */
#define H_FIORD_RCSID "@(#)$Id: ktlxml2fiord.sin 96802 2017-08-23 14:40:23Z wdeich $"

/* Entries in this file have the following structure:
 *
 * {    "long name",
 *      "keyword name",
 *      data_type,
 *      input function,
 *      output function,
 *      servers array,
 *      {units array} OR {enum values},
 *      quantity (if array-type),
 *      {fiord broads array},
 *      bin_to_asc function,
 *      asc_to_bin function,
 *      user (misc.) data
 * },
 */
{	"",
	"DISPERR",
	_int,
	input_disperr,
	(int (*)()) NULL,	/* Read-only keyword */
	disperr_servers,
	{"", "", "%d"},
	0,
	{ &inst_int_bcast_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"DISPMEM",
	_int,
	input_dispmem,
	(int (*)()) NULL,	/* Read-only keyword */
	dispmem_servers,
	{"kilobytes", "", "%d"},
	0,
	{ &inst_int_bcast_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"DISPMSG",
	_string,
	input_dispmsg,
	(int (*)()) NULL,	/* Read-only keyword */
	dispmsg_servers,
	{"", "", "%s"},
	0,
	{ &inst_string_bcast_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"DISPSTA",
	_enum,
	input_dispsta,
	(int (*)()) NULL,	/* Read-only keyword */
	dispsta_servers,
	{"Ready",
	 "Initializing",
	 "Shutting down"},
	0,
	{ &inst_int_bcast_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"DISPSTOP",
	_boolean,
	input_dispstop,
	output_dispstop,
	dispstop_servers,
	{"No",
	 "Yes"},
	0,
	{ &inst_int_bcast_kval_info,
	  &inst_int_resp2_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"TEST",
	_int,
	input_test,
	output_test,
	test_servers,
	{"", "", "%d"},
	0,
	{ &inst_int_bcast_kval_info,
	  &inst_int_resp2_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"TTMPOSX",
	_double,
	input_ttmposx,
	output_ttmposx,
	ttmposx_servers,
	{"", "", "%.3f"},
	0,
	{ &inst_double_bcast_kval_info,
	  &inst_double_resp2_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) btoa_number,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"UPTIME",
	_int,
	input_uptime,
	(int (*)()) NULL,	/* Read-only keyword */
	uptime_servers,
	{"seconds", "", "%d"},
	0,
	{ &inst_int_bcast_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

{	"",
	"VERSION",
	_string,
	input_version,
	(int (*)()) NULL,	/* Read-only keyword */
	version_servers,
	{"", "", "%s"},
	0,
	{ &inst_string_bcast_kval_info,
	  (FIORD_BROAD_INFO *) NULL },
	(int (*)()) NULL,
	(int (*)()) NULL,
	(void *) NULL
},

